import 'package:flutter/material.dart';

const Color thinGrennColor = Color(0xff16B26B);
const Color primaryColor = thinGrennColor;
const Color purpleColor = Color(0xff9370DB);
const Color secondryColor = purpleColor;
const Color backgroundColor = Color(0xffF3F5FA);
const Color backGroundColor = backgroundColor;
const Color lightGreyColor = Color(0xff5B7083);
const Color bordrColor = lightGreyColor;
const Color whitecolor = Colors.white;
const Color articalColor = Color(0xff515C6F);
const Color pinkColor = Colors.pink;
const Color secondarybuttonColor = pinkColor;
const Color transparentColor = Colors.transparent;
const Color borderColor = Color(0xffADB5BD);
const Color blackColor = Colors.black;
const Color filledColor = Colors.grey;
const Color textfiledBorderColor = Colors.greenAccent;
const Color titleColor = Color(0xff4A4A4A);
